window.LPL=(()=>{const deep={
"ANALYZE":{mode:"ANALYZE",intent:"Diagnose how the selected passage works without rewriting it.",g:["Explain POV, tension, subtext, pacing, description, emotional movement and likely weaknesses."]},
"TENS+":{mode:"EDIT",intent:"Increase narrative tension while preserving facts, events, POV, outcome and character intent.",g:["Increase consequential uncertainty.","Prefer information asymmetry, delayed confirmation, narrowing options or conflicting objectives.","Do not merely add ominous adjectives."]},
"TENS-":{mode:"EDIT",intent:"Reduce immediate tension without flattening character or deleting necessary information.",g:["Increase breathing room, clarity or reflection without removing essential stakes."]},
"SUB+":{mode:"EDIT",intent:"Increase discrepancy between surface language/behavior and underlying wants, fears, beliefs or motives.",g:["Use omission, gesture, indirection, contradiction or restrained response."]},
"DEEPEN":{mode:"EDIT",intent:"Increase psychological, emotional, conceptual or sensory complexity without changing the fundamental event.",g:["Add specificity rather than verbosity."]},
"COMPRESS":{mode:"EDIT",intent:"Reduce narrative space while preserving causality, essential information, voice and emotional function.",g:["Remove repetition and low-value explanation."]}};
function generic(c){return{mode:"EDIT",intent:`Apply ${c} as a coherent literary operation to the selection.`,g:["Interpret it through literary craft, not literal keyword insertion.","Preserve canon, POV, established facts and character continuity unless explicitly overridden."]}}
function compileStack(stack,natural,text){let items=stack.length?stack:[{code:"ANALYZE",label:"Analyze",strength:.5,target:"Selection"}],mode=items.every(x=>(deep[x.code]||generic(x.code)).mode==="ANALYZE")?"ANALYZE":"EDIT",L=[`MODE[${mode}]`,"TARGET[selected]","","OPERATOR_STACK {"];items.forEach((x,i)=>L.push(`  ${i+1}. ${x.code} { strength=${x.strength.toFixed(2)} target=${x.target||"Selection"} }`));L.push("}","","GLOBAL_PRESERVE {","  established facts","  canon","  POV","  character continuity","}");items.forEach(x=>{let d=deep[x.code]||generic(x.code);L.push("",`OPERATOR[${x.code}] {`,`  INTENT: ${d.intent}`,"  GUIDANCE:");d.g.forEach(g=>L.push("    "+g));L.push("}")});if(natural&&natural.trim())L.push("","AUTHOR_DIRECTION {","  "+natural.trim(),"}");return{operation:items.map(x=>x.code).join("+"),operators:items,mode,lpl:L.join("\n"),selected_text:text||"",instruction:natural||""}}
function localAnalyze(t){if(!t||!t.trim())return"No text selected.";let w=t.trim().split(/\s+/),s=t.split(/[.!?]+/).filter(x=>x.trim());return`Length: ${w.length} words; ${s.length||1} sentence(s). Deep literary diagnosis requires the configured AI model.`}
return{compileStack,localAnalyze}})();