(function(){
let selectedText="",catalog={},stack=[],busy=false;
const defaultFavs=["ANALYZE","TENS+","SUB+","DEEPEN","COMPRESS","DESC+"],$=id=>document.getElementById(id);
function status(m,k="neutral"){let e=$("status");e.textContent=m;e.className="status "+k}
function favs(){try{return JSON.parse(localStorage.getItem("lpl_favs"))||defaultFavs}catch(e){return defaultFavs}}
function saveFavs(x){localStorage.setItem("lpl_favs",JSON.stringify(x))}
function allOps(){let a=[];Object.entries(catalog).forEach(([cat,ops])=>ops.forEach(([code,label])=>a.push({cat,code,label})));return a}
function labelFor(c){let x=allOps().find(o=>o.code===c);return x?x.label:c}
function renderFavs(){let e=$("favorites");e.innerHTML="";favs().forEach(c=>{let b=document.createElement("button");b.textContent=labelFor(c);b.onclick=()=>addOp(c);e.appendChild(b)})}
function addOp(c){stack.push({code:c,label:labelFor(c),strength:.65,target:"Selection"});renderStack();status(labelFor(c)+" added.","ok")}
function renderStack(){let e=$("stack");e.innerHTML="";if(!stack.length){e.innerHTML='<div class="empty">No operators yet. Choose a pinned operator or open the Operator Library.</div>';build();return}stack.forEach((x,i)=>{let r=document.createElement("div");r.className="stackItem";r.innerHTML=`<div><b>${x.label}</b><div class="opCode">${x.code} · ${x.strength.toFixed(2)}</div></div><input type="range" min="0" max="1" step=".05" value="${x.strength}"><button>×</button>`;r.querySelector("input").oninput=v=>{x.strength=parseFloat(v.target.value);r.querySelector(".opCode").textContent=`${x.code} · ${x.strength.toFixed(2)}`;build()};r.querySelector("button").onclick=()=>{stack.splice(i,1);renderStack()};e.appendChild(r)});build()}
function renderLibrary(f=""){let n=f.toLowerCase(),e=$("library");e.innerHTML="";Object.entries(catalog).forEach(([cat,ops])=>{let shown=ops.filter(([c,l])=>(c+" "+l+" "+cat).toLowerCase().includes(n));if(!shown.length)return;let s=document.createElement("div");s.className="category";s.innerHTML=`<div class="catTitle">${cat}</div>`;shown.forEach(([c,l])=>{let row=document.createElement("div"),is=favs().includes(c);row.className="opRow";row.innerHTML=`<div><div>${l}</div><div class="opCode">${c}</div></div><button class="star">${is?"★":"☆"}</button><button class="add">Add</button>`;row.querySelector(".add").onclick=()=>addOp(c);row.querySelector(".star").onclick=()=>{let a=favs();a=is?a.filter(x=>x!==c):[...a,c];saveFavs(a);renderFavs();renderLibrary($("search").value)};s.appendChild(row)});e.appendChild(s)})}
function build(){let p=LPL.compileStack(stack,$("instruction").value,selectedText);$("lpl").value=p.lpl;return p}
function setSelection(t){selectedText=t||"";$("selected").value=selectedText;let n=selectedText.trim()?selectedText.trim().split(/\s+/).length:0;$("selectionMeta").textContent=n?`${n} words selected.`:"No selection.";build();status(n?"Selection loaded.":"Select manuscript text, then press ↻.",n?"ok":"warn")}
function getSel(){window.Asc.plugin.sendToPlugin("onLplRefreshSelection",{})}
function generate(){if(busy)return;if(!selectedText.trim()){status("Select manuscript text first.","warn");return}let p=build();busy=true;$("send").disabled=true;status("Generating preview with your ONLYOFFICE AI model…","neutral");window.Asc.plugin.sendToPlugin("onLplGenerate",p)}
function openCompare(){$("modalOriginal").value=selectedText;$("modalRevision").value=$("preview").value;$("modalExplanation").textContent=$("explanation").textContent;$("compareModal").classList.remove("hidden")}
function closeCompare(){$("compareModal").classList.add("hidden")}
function accept(v){let r=(v!==undefined?v:$("preview").value)||"";if(!r.trim())return;window.Asc.plugin.sendToPlugin("onLplAccept",{revision:r});status("Applying accepted revision…","neutral")}
function reject(){$("preview").value="";$("explanation").textContent="";$("accept").disabled=true;$("reject").disabled=true;closeCompare();status("Revision discarded. Manuscript unchanged.","ok")}
window.Asc.plugin.init=async function(){catalog=await fetch("operator-catalog.json").then(r=>r.json());renderFavs();renderLibrary();renderStack();window.Asc.plugin.sendToPlugin("onLplReady",{})}
window.Asc.plugin.attachEvent("onLplSelection",d=>setSelection((d&&d.text)||""));
window.Asc.plugin.attachEvent("onLplResult",d=>{busy=false;$("send").disabled=false;if(!d||d.error){status((d&&d.error)||"AI request failed. Manuscript unchanged.","error");return}if(d.analysis){$("preview").value="";$("explanation").textContent=d.analysis;$("accept").disabled=true;$("reject").disabled=true;status("Analysis received.","ok");return}$("preview").value=d.revision||"";$("explanation").textContent=d.explanation||"";let ok=!!$("preview").value.trim();$("accept").disabled=!ok;$("reject").disabled=!ok;if(ok){status("Revision ready. Manuscript unchanged until Accept.","ok");openCompare()}else status("AI returned no revision. Manuscript unchanged.","warn")});
window.Asc.plugin.attachEvent("onLplAccepted",d=>{closeCompare();status((d&&d.ok)?"Revision inserted.":"Could not insert revision.",(d&&d.ok)?"ok":"error");if(d&&d.ok){$("preview").value="";$("explanation").textContent="";$("accept").disabled=true;$("reject").disabled=true;getSel()}});
document.addEventListener("DOMContentLoaded",()=>{$("refresh").onclick=getSel;$("openLibrary").onclick=()=>{$("libraryModal").classList.remove("hidden");$("search").focus()};$("closeLibrary").onclick=()=>$("libraryModal").classList.add("hidden");$("search").oninput=e=>renderLibrary(e.target.value);$("build").onclick=()=>{build();status("LPL compiled.","ok")};$("send").onclick=generate;$("instruction").oninput=build;$("expandPreview").onclick=openCompare;$("closeModal").onclick=closeCompare;$("modalRevision").oninput=()=>{$("preview").value=$("modalRevision").value};$("modalAccept").onclick=()=>accept($("modalRevision").value);$("modalReject").onclick=reject;$("accept").onclick=()=>accept();$("reject").onclick=reject});
})();
